#  Image rotation and translation

In [2]:
import cv2

In [3]:
import numpy as np

In [4]:
im1=cv2.imread("C:/Users/admin/Downloads/purple.jpg")

In [5]:
im1

array([[[ 50,  42,  49],
        [ 50,  42,  49],
        [ 50,  42,  49],
        ...,
        [ 46, 114,  55],
        [ 46, 114,  55],
        [ 46, 114,  55]],

       [[ 50,  42,  49],
        [ 50,  42,  49],
        [ 50,  42,  49],
        ...,
        [ 46, 114,  55],
        [ 46, 114,  55],
        [ 46, 114,  55]],

       [[ 50,  42,  49],
        [ 50,  42,  49],
        [ 50,  42,  49],
        ...,
        [ 46, 114,  55],
        [ 46, 114,  55],
        [ 46, 114,  55]],

       ...,

       [[ 45,  34,  44],
        [ 45,  34,  44],
        [ 46,  35,  45],
        ...,
        [ 47,  36,  46],
        [ 47,  36,  46],
        [ 50,  35,  43]],

       [[ 45,  34,  44],
        [ 45,  34,  44],
        [ 45,  34,  44],
        ...,
        [ 47,  36,  46],
        [ 47,  36,  46],
        [ 48,  35,  43]],

       [[ 47,  33,  44],
        [ 47,  33,  44],
        [ 47,  33,  44],
        ...,
        [ 45,  34,  44],
        [ 45,  34,  44],
        [ 45,  34,  42]]

In [6]:
shp=im1.shape
print(shp)

(225, 225, 3)


In [7]:
height,width=im1.shape[:2]
print(height)
print(width)

225
225


In [8]:
cent=(height/2,width/2)
cent

(112.5, 112.5)

In [9]:
rotation_matrix=cv2.getRotationMatrix2D(center=cent,angle=25,scale=0.5)

In [10]:
print(rotation_matrix)

[[ 0.45315389  0.21130913 37.74790976]
 [-0.21130913  0.45315389 85.2924642 ]]


In [11]:
rotated_im=cv2.warpAffine(src=im1,M=rotation_matrix,dsize=(width,height))

In [12]:
cv2.imshow('original image',im1)
cv2.waitKey(0)
cv2.imshow('rotated image',rotated_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

# translation matrix

In [13]:
tx,ty=width/2,height/2


In [14]:
Translation_matrix=np.array([[1,0,tx],[0,1,ty]])

In [15]:
Translation_matrix

array([[  1. ,   0. , 112.5],
       [  0. ,   1. , 112.5]])

In [16]:
Trans_im=cv2.warpAffine(src=im1,M=Translation_matrix,dsize=(width,height))

In [17]:
cv2.imshow('original image',im1)
cv2.waitKey(0)
cv2.imshow('Transimage',Trans_im)
cv2.waitKey(0)
cv2.destroyAllWindows()