# K-means clustering

# Importing libraries


In [1]:
import cv2
import numpy as np

# Reading images

In [2]:
img=cv2.imread("C:/Users/admin/Downloads/dog.jpg")
img

array([[[ 34,  50,  56],
        [ 35,  51,  57],
        [ 37,  53,  59],
        ...,
        [ 33,  39,  46],
        [ 33,  39,  46],
        [ 33,  39,  46]],

       [[ 34,  50,  56],
        [ 35,  51,  57],
        [ 37,  53,  59],
        ...,
        [ 33,  39,  46],
        [ 33,  39,  46],
        [ 33,  39,  46]],

       [[ 34,  50,  56],
        [ 36,  52,  58],
        [ 37,  53,  59],
        ...,
        [ 33,  39,  46],
        [ 33,  39,  46],
        [ 33,  39,  46]],

       ...,

       [[ 54, 148, 207],
        [ 70, 162, 215],
        [ 50, 132, 179],
        ...,
        [140, 163, 219],
        [ 28,  48,  95],
        [ 34,  49,  88]],

       [[ 21, 113, 172],
        [ 41, 129, 183],
        [ 29, 109, 156],
        ...,
        [ 89, 113, 167],
        [ 19,  37,  84],
        [ 32,  45,  83]],

       [[  0,  87, 146],
        [ 17, 105, 159],
        [ 15,  93, 140],
        ...,
        [102, 126, 180],
        [ 17,  36,  81],
        [ 39,  52,  90]]

# RGB Conversion

In [3]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# Reshape

In [4]:
vec=imgrgb.reshape((-1,3))
vec

array([[ 56,  50,  34],
       [ 57,  51,  35],
       [ 59,  53,  37],
       ...,
       [180, 126, 102],
       [ 81,  36,  17],
       [ 90,  52,  39]], dtype=uint8)

# Float conversion

In [5]:
vec=np.float32(vec)
vec

array([[ 56.,  50.,  34.],
       [ 57.,  51.,  35.],
       [ 59.,  53.,  37.],
       ...,
       [180., 126., 102.],
       [ 81.,  36.,  17.],
       [ 90.,  52.,  39.]], dtype=float32)

# Iteration Termination Criteria

In [6]:
criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,100,1)

# Cluster conditions

In [7]:
k = 3
attempts=100

# K-means Clustering

In [8]:
compactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[ 76.54822 ,  56.325275,  36.86668 ],
       [242.03741 , 192.91129 , 143.65546 ],
       [177.2623  , 115.73308 ,  79.07251 ]], dtype=float32)

# unit conversion

In [9]:
center=np.uint8(center)
center

array([[ 76,  56,  36],
       [242, 192, 143],
       [177, 115,  79]], dtype=uint8)

# flattening and reshape

In [10]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[ 76,  56,  36],
        [ 76,  56,  36],
        [ 76,  56,  36],
        ...,
        [ 76,  56,  36],
        [ 76,  56,  36],
        [ 76,  56,  36]],

       [[ 76,  56,  36],
        [ 76,  56,  36],
        [ 76,  56,  36],
        ...,
        [ 76,  56,  36],
        [ 76,  56,  36],
        [ 76,  56,  36]],

       [[ 76,  56,  36],
        [ 76,  56,  36],
        [ 76,  56,  36],
        ...,
        [ 76,  56,  36],
        [ 76,  56,  36],
        [ 76,  56,  36]],

       ...,

       [[177, 115,  79],
        [177, 115,  79],
        [177, 115,  79],
        ...,
        [242, 192, 143],
        [ 76,  56,  36],
        [ 76,  56,  36]],

       [[177, 115,  79],
        [177, 115,  79],
        [177, 115,  79],
        ...,
        [177, 115,  79],
        [ 76,  56,  36],
        [ 76,  56,  36]],

       [[ 76,  56,  36],
        [177, 115,  79],
        [ 76,  56,  36],
        ...,
        [177, 115,  79],
        [ 76,  56,  36],
        [ 76,  56,  36]]

# original and segmented image

In [11]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()